import * as mongoose from 'mongoose';
import * as path from 'path';
import * as dotenv from 'dotenv';

dotenv.config({ path: path.resolve(__dirname, '../../.env') });

const SetSchema = new mongoose.Schema({
  setCode: { type: String, required: true, unique: true },
  name: { type: String, required: true },
  description: String,
  era: { type: String, required: true },
  block: String,
  totalCards: { type: Number, default: 0 },
  imageUrl: String,
  releaseYear: Number,
});

const setsData = [
  // ── SHOBU ERA ─────────────────────────────────────────────────────────────
  // Beginner's Block
  {
    setCode: 'DM-01',
    name: 'Base Set',
    description: 'The original Duel Masters set introducing the five civilizations: Light, Water, Darkness, Fire, and Nature. Features iconic early cards including Bolshack Dragon and Aqua Hulcus.',
    era: 'shobu',
    block: "Beginner's Block",
    totalCards: 110,
    releaseYear: 2002,
  },
  {
    setCode: 'DM-02',
    name: 'Master of Evolution',
    description: 'Expands the card pool with new evolution creatures and powerful spells. Introduces the concept of evolution creatures that grow from existing ones in the battle zone.',
    era: 'shobu',
    block: "Beginner's Block",
    totalCards: 55,
    releaseYear: 2002,
  },
  {
    setCode: 'DM-03',
    name: 'Master of Destruction',
    description: 'Focuses on aggressive tactics and destruction effects. Features stronger fire and darkness cards alongside new multi-civilization strategies.',
    era: 'shobu',
    block: "Beginner's Block",
    totalCards: 55,
    releaseYear: 2003,
  },
  {
    setCode: 'DM-04',
    name: 'Challenge of Black Shadow',
    description: 'Introduces the Black Shadow series with powerful darkness-aligned cards. Deepens the rivalry between light and darkness with new cards featuring Shadow creatures.',
    era: 'shobu',
    block: "Beginner's Block",
    totalCards: 55,
    releaseYear: 2003,
  },
  {
    setCode: 'DM-05',
    name: 'Return of the Survivor',
    description: "Continues the Survivor creature type introduced in earlier sets. Features cards with the Survivor ability that share their effects with other Survivors in the battle zone.",
    era: 'shobu',
    block: "Beginner's Block",
    totalCards: 55,
    releaseYear: 2003,
  },
  // Fighting Spirit Saga
  {
    setCode: 'DM-06',
    name: 'Invincible Soul',
    description: 'Opens the Fighting Spirit Saga block. Introduces new powerful creatures and expands on the civilization themes with multi-cost powerhouses.',
    era: 'shobu',
    block: 'Fighting Spirit Saga',
    totalCards: 55,
    releaseYear: 2004,
  },
  {
    setCode: 'DM-07',
    name: 'Invincible Charge',
    description: 'Continues the Fighting Spirit Saga with new speed attacker and blocker mechanics. Features powerful dragon creatures that would define competitive play.',
    era: 'shobu',
    block: 'Fighting Spirit Saga',
    totalCards: 55,
    releaseYear: 2004,
  },
  {
    setCode: 'DM-08',
    name: 'Invincible Legend',
    description: 'The climax of the first Invincible trilogy. Introduces legendary creatures and milestone cards that push the power level of each civilization.',
    era: 'shobu',
    block: 'Fighting Spirit Saga',
    totalCards: 55,
    releaseYear: 2004,
  },
  {
    setCode: 'DM-09',
    name: 'Invincible Blood',
    description: 'Closes the Fighting Spirit Saga block with a focus on vampire and blood-themed darkness creatures alongside powerful cross-civilization strategies.',
    era: 'shobu',
    block: 'Fighting Spirit Saga',
    totalCards: 55,
    releaseYear: 2004,
  },
  // Holy Fist Saga
  {
    setCode: 'DM-10',
    name: 'Eternal Arms',
    description: 'Opens the Holy Fist Saga with a focus on weapon-equipped creatures and armored knights. Introduces new cross-civilization synergies.',
    era: 'shobu',
    block: 'Holy Fist Saga',
    totalCards: 55,
    releaseYear: 2004,
  },
  {
    setCode: 'DM-11',
    name: 'Eternal Wave',
    description: 'Continues the Holy Fist Saga with water and light themed cards. Features wave-based effects that bounce and cycle cards for powerful combo plays.',
    era: 'shobu',
    block: 'Holy Fist Saga',
    totalCards: 55,
    releaseYear: 2005,
  },
  {
    setCode: 'DM-12',
    name: 'Eternal Vortex',
    description: 'Introduces vortex-based abilities with discard and destruction synergies. Notable for the introduction of powerful destruction spells.',
    era: 'shobu',
    block: 'Holy Fist Saga',
    totalCards: 55,
    releaseYear: 2005,
  },
  {
    setCode: 'DM-13',
    name: 'Eternal Phoenix',
    description: 'The conclusion of the Holy Fist Saga featuring the mighty Phoenix creatures with abilities to return from the graveyard and overwhelm opponents.',
    era: 'shobu',
    block: 'Holy Fist Saga',
    totalCards: 55,
    releaseYear: 2005,
  },
  // Reincarnation Saga
  {
    setCode: 'DM-14',
    name: 'Generate Gear',
    description: 'Opens the Reincarnation Saga with a mechanical gear theme. Introduces cross gear cards — equipment that can be attached to creatures to enhance their abilities.',
    era: 'shobu',
    block: 'Reincarnation Saga',
    totalCards: 55,
    releaseYear: 2005,
  },
  {
    setCode: 'DM-15',
    name: 'Secret of Hidden Gear',
    description: 'Expands on the cross gear mechanic with hidden and secret-themed gears. Features powerful evolution cards that synergize with equipped cross gears.',
    era: 'shobu',
    block: 'Reincarnation Saga',
    totalCards: 55,
    releaseYear: 2005,
  },
  {
    setCode: 'DM-16',
    name: 'Origin of Perfect Gear',
    description: 'Introduces the concept of perfect evolution through cross gears. Features apex cross gear cards that represent the pinnacle of mechanical evolution.',
    era: 'shobu',
    block: 'Reincarnation Saga',
    totalCards: 55,
    releaseYear: 2006,
  },
  {
    setCode: 'DM-17',
    name: 'The Over-Technocross',
    description: 'Concludes the Reincarnation Saga with the Over-Technocross, combining technology and ancient power. Features the legendary Evolution cross creatures.',
    era: 'shobu',
    block: 'Reincarnation Saga',
    totalCards: 55,
    releaseYear: 2006,
  },
  // Phoenix Saga
  {
    setCode: 'DM-19',
    name: 'Spectacle Nova',
    description: 'Opens the Phoenix Saga with the introduction of Neo Evolution creatures and powerful nova-class cards. A turning point in the game with multi-civilization evolution.',
    era: 'shobu',
    block: 'Phoenix Saga',
    totalCards: 120,
    releaseYear: 2006,
  },
  {
    setCode: 'DM-20',
    name: 'The Ultimate Nova',
    description: 'Continues the Phoenix Saga with ultimate-tier creatures. Features some of the most powerful evolution creatures in the early game history.',
    era: 'shobu',
    block: 'Phoenix Saga',
    totalCards: 55,
    releaseYear: 2006,
  },
  {
    setCode: 'DM-21',
    name: 'History of Devil Nova',
    description: 'Explores the dark side of the Phoenix Saga with devil-themed creatures. Introduces powerful darkness cross-civilization creatures with game-ending abilities.',
    era: 'shobu',
    block: 'Phoenix Saga',
    totalCards: 55,
    releaseYear: 2007,
  },
  {
    setCode: 'DM-22',
    name: 'The Dragonic Nova',
    description: 'Focuses on the dragon tribe with powerful dragonic nova-class creatures. Features fire-aligned dragons with massive power and game-winning abilities.',
    era: 'shobu',
    block: 'Phoenix Saga',
    totalCards: 55,
    releaseYear: 2007,
  },
  {
    setCode: 'DM-23',
    name: 'The End of the Universe',
    description: 'The climax of the Phoenix Saga with universe-ending threats and apocalyptic creatures. Features the mighty Phoenix creature type at its most powerful.',
    era: 'shobu',
    block: 'Phoenix Saga',
    totalCards: 55,
    releaseYear: 2007,
  },
  // God Apex Saga
  {
    setCode: 'DM-24',
    name: 'Violence Heaven',
    description: 'Opens the God Apex Saga introducing the God creature type — beings of immense power that link together to form multi-part deities.',
    era: 'shobu',
    block: 'God Apex Saga',
    totalCards: 120,
    releaseYear: 2007,
  },
  {
    setCode: 'DM-25',
    name: 'Violence Creator',
    description: 'Expands the God Apex Saga with creator-class god creatures. Introduces new link abilities and powerful god spells that reshape the battle zone.',
    era: 'shobu',
    block: 'God Apex Saga',
    totalCards: 55,
    releaseYear: 2007,
  },
  {
    setCode: 'DM-26',
    name: 'Dragonic Wars',
    description: 'Focuses on the war between dragon gods. Features powerful dragon-god hybrid creatures from multiple civilizations engaged in epic battles.',
    era: 'shobu',
    block: 'God Apex Saga',
    totalCards: 55,
    releaseYear: 2008,
  },
  {
    setCode: 'DM-27',
    name: 'Perfect Heaven',
    description: 'Concludes the God Apex Saga with the ascension to Perfect Heaven. Features the ultimate god creatures combining all five civilizations.',
    era: 'shobu',
    block: 'God Apex Saga',
    totalCards: 55,
    releaseYear: 2008,
  },
  // Sengoku Saga
  {
    setCode: 'DM-28',
    name: 'Battle Galaxy',
    description: 'Opens the Sengoku Saga with a galaxy-spanning battle theme. Introduces Alien creatures and powerful galactic spells that transcend civilization boundaries.',
    era: 'shobu',
    block: 'Sengoku Saga',
    totalCards: 120,
    releaseYear: 2008,
  },
  {
    setCode: 'DM-29',
    name: 'Rock-on Heroes',
    description: 'Introduces the Rock creature type and rock-music themed heroes. Features energetic fire and nature cards with powerful speed attacker abilities.',
    era: 'shobu',
    block: 'Sengoku Saga',
    totalCards: 55,
    releaseYear: 2008,
  },
  {
    setCode: 'DM-30',
    name: 'Ultra Duel',
    description: 'Marks the mid-point of the Sengoku Saga with ultra-powered duel creatures. Features cross-civilization ultra-evolution cards with dramatic game-ending effects.',
    era: 'shobu',
    block: 'Sengoku Saga',
    totalCards: 55,
    releaseYear: 2008,
  },
  {
    setCode: 'DM-31',
    name: 'Greatest Champion',
    description: 'Concludes the Sengoku Saga with champion-class creatures. Features the greatest warriors of all five civilizations in their most powerful forms.',
    era: 'shobu',
    block: 'Sengoku Saga',
    totalCards: 55,
    releaseYear: 2009,
  },
  // Divine Evolution Saga
  {
    setCode: 'DM-32',
    name: 'Evolution Saga',
    description: 'Opens the Divine Evolution Saga reintroducing evolution as the central theme. Brings back classic evolution creatures in divine new forms.',
    era: 'shobu',
    block: 'Divine Evolution Saga',
    totalCards: 120,
    releaseYear: 2009,
  },
  {
    setCode: 'DM-33',
    name: 'Rising Dragon',
    description: 'Focuses on the ascension of dragon creatures through divine evolution. Features new dragon evolution chains that end in overwhelming power.',
    era: 'shobu',
    block: 'Divine Evolution Saga',
    totalCards: 55,
    releaseYear: 2009,
  },
  {
    setCode: 'DM-34',
    name: 'Cross Generation',
    description: 'Bridges generations of Duel Masters creatures with cross-generational evolution. Features callbacks to iconic early cards in powerful evolved forms.',
    era: 'shobu',
    block: 'Divine Evolution Saga',
    totalCards: 55,
    releaseYear: 2009,
  },
  {
    setCode: 'DM-35',
    name: 'Neverending Saga',
    description: 'The climax of the Shobu Era concluding the Divine Evolution Saga. Features creatures that represent the culmination of years of Duel Masters history.',
    era: 'shobu',
    block: 'Divine Evolution Saga',
    totalCards: 55,
    releaseYear: 2009,
  },
  // Psychic Shock
  {
    setCode: 'DM-36',
    name: 'Psychic Shock',
    description: 'Opens the Psychic Shock block introducing Psychic creatures — powerful beings released from another dimension by awakening existing creatures.',
    era: 'shobu',
    block: 'Psychic Shock',
    totalCards: 120,
    releaseYear: 2010,
  },
  {
    setCode: 'DM-37',
    name: 'Dark Emperor',
    description: 'Continues the Psychic Shock block with dark emperor psychic creatures. Features powerful darkness psychic creatures that dominate the battle zone.',
    era: 'shobu',
    block: 'Psychic Shock',
    totalCards: 55,
    releaseYear: 2010,
  },
  {
    setCode: 'DM-38',
    name: 'Angelic Wars',
    description: 'Focuses on angelic psychic creatures from the light civilization. Features massive light psychic creatures with powerful blocker and untap abilities.',
    era: 'shobu',
    block: 'Psychic Shock',
    totalCards: 55,
    releaseYear: 2010,
  },
  {
    setCode: 'DM-39',
    name: 'Psychic Splash',
    description: 'Concludes the Shobu Era Psychic Shock block with a final wave of psychic creatures. Marks the end of Shobu\'s journey as the main protagonist.',
    era: 'shobu',
    block: 'Psychic Shock',
    totalCards: 55,
    releaseYear: 2011,
  },

  // ── KATTA ERA ─────────────────────────────────────────────────────────────
  // Episode 1
  {
    setCode: 'DMR-01',
    name: 'First Contact',
    description: 'Launches the Katta Era and the DMR series. Introduces new hero Katta Kirifuda and brings the Dragon Saga, featuring powerful dragon creatures from multiple civilizations.',
    era: 'katta',
    block: 'Episode 1',
    totalCards: 120,
    releaseYear: 2011,
  },
  {
    setCode: 'DMR-02',
    name: 'Dark Side',
    description: 'Explores the dark side of the Katta Era. Features powerful darkness and water cards with new dragon subtypes and multi-civilization strategies.',
    era: 'katta',
    block: 'Episode 1',
    totalCards: 55,
    releaseYear: 2011,
  },
  {
    setCode: 'DMR-03',
    name: 'Gaial Victory',
    description: 'Centers on the Gaial dragon lineage with victory-themed creatures. Features Gaial Kaiser and powerful fire civilization dragons.',
    era: 'katta',
    block: 'Episode 1',
    totalCards: 55,
    releaseYear: 2012,
  },
  {
    setCode: 'DMR-04',
    name: 'Rising Hope',
    description: 'Concludes Episode 1 with rising-hope themed cards. Features new evolution creatures and powerful cross-civilization spells.',
    era: 'katta',
    block: 'Episode 1',
    totalCards: 55,
    releaseYear: 2012,
  },
  // Episode 2
  {
    setCode: 'DMR-05',
    name: 'Golden Age',
    description: 'Opens Episode 2 with golden-age themed powerful creatures. Introduces new gold-colored legendary creatures from the light civilization.',
    era: 'katta',
    block: 'Episode 2',
    totalCards: 120,
    releaseYear: 2012,
  },
  {
    setCode: 'DMR-06',
    name: 'Victory Rush',
    description: 'Features rush-based aggressive strategies. Introduces Victory cards — rare and powerful creatures with game-changing abilities.',
    era: 'katta',
    block: 'Episode 2',
    totalCards: 55,
    releaseYear: 2012,
  },
  {
    setCode: 'DMR-07',
    name: 'Golden Dragon',
    description: 'Focuses on golden dragon creatures with massive power. Features the legendary Bolshack NEX and other iconic dragon evolutions.',
    era: 'katta',
    block: 'Episode 2',
    totalCards: 55,
    releaseYear: 2013,
  },
  {
    setCode: 'DMR-08',
    name: 'Great Miracle',
    description: 'Concludes Episode 2 with miraculous great creatures. Features powerful multi-civilization cards and dramatic win conditions.',
    era: 'katta',
    block: 'Episode 2',
    totalCards: 55,
    releaseYear: 2013,
  },
  // Episode 3
  {
    setCode: 'DMR-09',
    name: 'Rage vs God',
    description: 'Opens Episode 3 pitting raw rage against divine power. Features the clash between aggressive dragons and powerful god creatures.',
    era: 'katta',
    block: 'Episode 3',
    totalCards: 120,
    releaseYear: 2013,
  },
  {
    setCode: 'DMR-10',
    name: 'Dead & Beat',
    description: 'Brings a punk-rock theme to Duel Masters with dead and beat creatures. Features undead darkness creatures battling against rhythm-based cards.',
    era: 'katta',
    block: 'Episode 3',
    totalCards: 55,
    releaseYear: 2013,
  },
  {
    setCode: 'DMR-11',
    name: 'Ultra Victory Master',
    description: 'Features ultra Victory-rarity cards with the most powerful creatures of Episode 3. The Ultra Victory cards define tournament play for this era.',
    era: 'katta',
    block: 'Episode 3',
    totalCards: 55,
    releaseYear: 2014,
  },
  {
    setCode: 'DMR-12',
    name: 'Omega Climax',
    description: 'Concludes Episode 3 with an omega-level climax. Features the mightiest creatures of the episode in a explosive final chapter.',
    era: 'katta',
    block: 'Episode 3',
    totalCards: 55,
    releaseYear: 2014,
  },
  // Dragon Saga
  {
    setCode: 'DMR-13',
    name: 'Dragsolution Gaiginga',
    description: 'Opens the Dragon Saga with the Dragsolution mechanic. Features Gaiginga and powerful Dragon Saga creatures that Dragsolution-evolve into game-enders.',
    era: 'katta',
    block: 'Dragon Saga',
    totalCards: 120,
    releaseYear: 2014,
  },
  {
    setCode: 'DMR-14',
    name: 'Wild Dragon Gaiglen',
    description: 'Continues the Dragon Saga with wild dragon creatures. Features Gaiglen and untamed nature/fire dragon hybrids with powerful Dragsolution forms.',
    era: 'katta',
    block: 'Dragon Saga',
    totalCards: 55,
    releaseYear: 2014,
  },
  {
    setCode: 'DMR-15',
    name: 'Double Swords Ohginga',
    description: 'Features the double-sword wielding dragon Ohginga. Introduces powerful dual-civilization sword-equipped dragon creatures.',
    era: 'katta',
    block: 'Dragon Saga',
    totalCards: 55,
    releaseYear: 2015,
  },
  {
    setCode: 'DMR-16極',
    name: 'Super Battle Guynext x Goku',
    description: 'One of two simultaneous Dragon Saga climax sets. Features the extreme (極) path with Guynext and powerful fire-nature dragon finale creatures.',
    era: 'katta',
    block: 'Dragon Saga',
    totalCards: 55,
    releaseYear: 2015,
  },
  {
    setCode: 'DMR-16真',
    name: 'Super Battle Guynext x Shin',
    description: 'The true (真) counterpart to DMR-16極. Features light-water dragon path creatures culminating in the true final form of Guynext.',
    era: 'katta',
    block: 'Dragon Saga',
    totalCards: 55,
    releaseYear: 2015,
  },
  // Revolution
  {
    setCode: 'DMR-17',
    name: 'Burning Dogiragon!!',
    description: 'Ignites the Revolution block with the burning spirit of Dogiragon. Introduces the Revolution and Final Revolution abilities on powerful creatures.',
    era: 'katta',
    block: 'Revolution',
    totalCards: 120,
    releaseYear: 2015,
  },
  {
    setCode: 'DMR-18',
    name: 'Seize the Moment, Miradante!!',
    description: 'Features the time-stopping Miradante and powerful temporal manipulation cards. Introduces the legendary Miradante Twelve.',
    era: 'katta',
    block: 'Revolution',
    totalCards: 55,
    releaseYear: 2015,
  },
  {
    setCode: 'DMR-19',
    name: 'Forbidden Dokindam X',
    description: 'Introduces the forbidden and sealed creature Dokindam X — a powerful forbidden card that was banned shortly after release due to its overwhelming power.',
    era: 'katta',
    block: 'Revolution',
    totalCards: 55,
    releaseYear: 2016,
  },
  {
    setCode: 'DMR-20',
    name: "Gyuujinmaru's True Identity!!",
    description: "Reveals Gyuujinmaru's true identity as the Revolution arc climaxes. Features the ultimate forms of Revolution creatures in an explosive finale.",
    era: 'katta',
    block: 'Revolution',
    totalCards: 55,
    releaseYear: 2016,
  },
  // Revolution Final
  {
    setCode: 'DMR-21',
    name: 'Team Hamukatsu and Dogiragon Buster',
    description: 'Opens Revolution Final with Team Hamukatsu and the upgraded Dogiragon Buster. Features team-based synergies and the powerful Buster evolution mechanic.',
    era: 'katta',
    block: 'Revolution Final',
    totalCards: 120,
    releaseYear: 2016,
  },
  {
    setCode: 'DMR-22',
    name: 'The World of Zero!! Blackout!!',
    description: 'Features a world plunged into zero darkness with blackout-themed creatures. Introduces Zero Civilization cards alongside powerful darkness mechanics.',
    era: 'katta',
    block: 'Revolution Final',
    totalCards: 55,
    releaseYear: 2016,
  },
  {
    setCode: 'DMR-23',
    name: 'Dogiragolden VS Dormageddon X',
    description: 'The ultimate clash concluding the Katta Era: the golden Dogiragolden battles the forbidden Dormageddon X. The final chapter of Katta\'s story.',
    era: 'katta',
    block: 'Revolution Final',
    totalCards: 55,
    releaseYear: 2017,
  },

  // ── JOE ERA ───────────────────────────────────────────────────────────────
  // Duel Masters
  {
    setCode: 'DMRP-01',
    name: 'Here Come the Jokers!!',
    description: 'Launches the Joe Era introducing protagonist Joe Kirifuda and the Jokers civilization — a new civilization of crazy, unpredictable creatures that break all the rules.',
    era: 'joe',
    block: 'Duel Masters',
    totalCards: 120,
    releaseYear: 2017,
  },
  {
    setCode: 'DMRP-02',
    name: 'All So Truly B·A·D Labyrinth!!',
    description: 'Explores the B.A.D. (Black, Alien, Darkness) labyrinth with powerful darkness and multi-civilization cards. Features dark labyrinth creatures and maze-based effects.',
    era: 'joe',
    block: 'Duel Masters',
    totalCards: 55,
    releaseYear: 2017,
  },
  {
    setCode: 'DMRP-03',
    name: 'Feeling Joejoe Meraventure!!',
    description: "Continues Joe's adventure with Joejoe-themed creatures. Features the Meraventure mechanic and powerful joker-based strategies.",
    era: 'joe',
    block: 'Duel Masters',
    totalCards: 55,
    releaseYear: 2017,
  },
  {
    setCode: 'DMRP-04裁',
    name: 'The Rise of Master Dragon!! ~Judgment for Justice~',
    description: 'One of two simultaneous sets focusing on the rise of the master dragon through justice. Features light-fire dragon creatures fighting for righteous judgment.',
    era: 'joe',
    block: 'Duel Masters',
    totalCards: 55,
    releaseYear: 2018,
  },
  {
    setCode: 'DMRP-04魔',
    name: 'The Rise of Master Dolszak!! ~Demon Phoenix of Moonless Night~',
    description: 'The dark counterpart featuring the demon phoenix Dolszak under a moonless night. Features darkness-water creatures with powerful Phoenix abilities.',
    era: 'joe',
    block: 'Duel Masters',
    totalCards: 55,
    releaseYear: 2018,
  },
  // Twinpact Series
  {
    setCode: 'DMRP-05',
    name: 'Gokai!! Joragon Go Fight!!',
    description: 'Opens the Twinpact Series introducing Twinpact cards — double-faced cards with both a creature and spell side. Features Joragon and powerful dual-nature cards.',
    era: 'joe',
    block: 'Twinpact Series',
    totalCards: 120,
    releaseYear: 2018,
  },
  {
    setCode: 'DMRP-06',
    name: 'Strike Back Galaxy 卍·Inferno·Annihilation!!',
    description: 'Features the galaxy-scale strike back with inferno-level annihilation cards. Introduces the 卍 (Maji) symbol cards with game-changing cosmic abilities.',
    era: 'joe',
    block: 'Twinpact Series',
    totalCards: 55,
    releaseYear: 2018,
  },
  {
    setCode: 'DMRP-07',
    name: 'Ghira Ghira Ghiramessiah and Finaling QX!!',
    description: 'Features the Ghiramessiah and the Finaling mechanic with QX creatures. Introduces powerful final evolution forms with double-sided Twinpact cards.',
    era: 'joe',
    block: 'Twinpact Series',
    totalCards: 55,
    releaseYear: 2018,
  },
  {
    setCode: 'DMRP-08',
    name: 'The Showdown! Baraghiara!! Invincible OraOra Ringfinity ∞',
    description: 'The climax showdown of the Twinpact Series featuring Baraghiara and infinite OraOra ring abilities. A landmark set with the powerful ∞ infinity creatures.',
    era: 'joe',
    block: 'Twinpact Series',
    totalCards: 55,
    releaseYear: 2019,
  },
  // Gacharange Series
  {
    setCode: 'DMRP-09',
    name: 'New Zone Was Born! Super GR and Orega Ora!!',
    description: 'Opens the Gacharange Series introducing the new Super Gacharange (GR) zone. GR creatures are shuffled into a special deck and revealed when triggered.',
    era: 'joe',
    block: 'Gacharange Series',
    totalCards: 120,
    releaseYear: 2019,
  },
  {
    setCode: 'DMRP-10',
    name: 'Blue C.A.P and Black DaiBanZai',
    description: 'Features the C.A.P. (Crazy Amazing Power) and DaiBanZai mechanics. Introduces powerful blue water and black darkness GR creatures.',
    era: 'joe',
    block: 'Gacharange Series',
    totalCards: 55,
    releaseYear: 2019,
  },
  {
    setCode: 'DMRP-11',
    name: "Zero Birth! Maji's Jornado 1059!!",
    description: "Features the birth of zero-civilization powered cards and Maji's epic Jornado 1059 journey. Introduces powerful zero-cost and zero-civilization GR creatures.",
    era: 'joe',
    block: 'Gacharange Series',
    totalCards: 55,
    releaseYear: 2019,
  },
  {
    setCode: 'DMRP-12',
    name: 'SuperSuperSuper Top! The Awakening Joghiragon vs. Zeeron Bang-Tan!',
    description: 'The Gacharange Series climax featuring the epic battle of Joghiragon vs Zeeron Bang-Tan. Features the ultimate GR creatures in an over-the-top showdown.',
    era: 'joe',
    block: 'Gacharange Series',
    totalCards: 55,
    releaseYear: 2019,
  },
  // Ten Kings
  {
    setCode: 'DMRP-13',
    name: 'Kirifuda x Onifuda King Wars!!!',
    description: 'Opens the Ten Kings block with the clash between Kirifuda and Onifuda. Introduces the King card rarity with powerful king-class creatures wielding immense power.',
    era: 'joe',
    block: 'Ten Kings',
    totalCards: 120,
    releaseYear: 2020,
  },
  {
    setCode: 'DMRP-14',
    name: 'Explosive Dragon x Explosive Rising Dynabolt!!!',
    description: 'Features explosive dragon creatures and the rising Dynabolt. Introduces powerful dragon kings and explosive effect chains.',
    era: 'joe',
    block: 'Ten Kings',
    totalCards: 55,
    releaseYear: 2020,
  },
  {
    setCode: 'DMRP-15',
    name: 'Phantom Dragon x Swift Attack Genmu Emperor!!!',
    description: "Features phantom dragon creatures and the swift-attacking Genmu Emperor. Introduces stealth and ambush mechanics alongside the Ten Kings' phantom warriors.",
    era: 'joe',
    block: 'Ten Kings',
    totalCards: 55,
    releaseYear: 2020,
  },
  {
    setCode: 'DMRP-16',
    name: 'The Hundred Kings x Evil King Oni Revolution!!!',
    description: 'Concludes the Ten Kings block with a hundred kings uprising and the evil king Oni Revolution. Features the mightiest king creatures in a revolutionary final battle.',
    era: 'joe',
    block: 'Ten Kings',
    totalCards: 55,
    releaseYear: 2020,
  },
  // The Rise of Kings
  {
    setCode: 'DMRP-17',
    name: 'RexStars and Dispector',
    description: 'Opens The Rise of Kings block introducing RexStars — legendary star creatures — and Dispectors, creatures assembled from disparate parts. A new era of power begins.',
    era: 'joe',
    block: 'The Rise of Kings',
    totalCards: 120,
    releaseYear: 2021,
  },
  {
    setCode: 'DMRP-18',
    name: 'Miracle Forbidden',
    description: 'Introduces miraculous yet forbidden cards in The Rise of Kings. Features powerful forbidden creatures alongside miracle-level spells and awakening mechanics.',
    era: 'joe',
    block: 'The Rise of Kings',
    totalCards: 55,
    releaseYear: 2021,
  },
  {
    setCode: 'DMRP-19',
    name: 'Eternal Premiums',
    description: 'Concludes the Joe Era with eternal premium creatures. Features the final chapter of the Joe Era with legendary eternal cards representing the best of all three eras.',
    era: 'joe',
    block: 'The Rise of Kings',
    totalCards: 55,
    releaseYear: 2021,
  },
];

async function seed() {
  const uri = process.env.MONGODB_URI || 'mongodb://localhost:27017/duel-masters';
  await mongoose.connect(uri);
  console.log('Connected to MongoDB');

  const SetModel = mongoose.model('sets', SetSchema);

  let upserted = 0;
  for (const set of setsData) {
    await SetModel.findOneAndUpdate({ setCode: set.setCode }, set, { upsert: true, new: true });
    upserted++;
  }

  console.log(`Seed complete: ${upserted} sets upserted`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
