export enum GamesEventsEnum {
    ADD_GAME = 'addGame',
    GET_GAME = 'getGame',
    GET_GAMES = 'getGames',
    JOIN_GAME = 'joinGame',
    LEAVE_GAME = 'leaveGame',
    CHALLENGE = 'challenge',
    SET_CHALLENGER = 'setChallenger',
    SET_FIRST_TO_GO = 'setFirstToGo',
    INVITER_LEFT = 'inviterLeft',
    GAMES_LIST = 'gamesList',
    GAME_INFO = 'gameInfo',
    USER_INFO = 'userInfo',
    RESET_GAME = 'resetGame',
    START_DUEL = 'startDuel',
    DUEL = 'duel',
}
