export enum GameEvents {
  GAME_CREATED = 'game_created',
  GAMES_LIST = 'games_list',
  GAME_JOINED = 'game_joined',
  GAME_LEFT = 'game_left',
  CHALLENGED = 'challenged',
  CHALLENGE_REVOKED = 'challenge_revoked',
  COIN_TOSS_RESULT = 'coin_toss_result',
  WHO_GOES_FIRST = 'who_goes_first',
  DUEL_STARTED = 'duel_started',
  GAME_STATE_UPDATE = 'game_state_update',
  CARD_DROPPED = 'card_dropped',
  CARD_TAPPED = 'card_tapped',
  CARD_UNTAPPED = 'card_untapped',
  PHASE_CHANGED = 'phase_changed',
  CHAT_MESSAGE = 'chat_message',
  GAME_ENDED = 'game_ended',
  ERROR = 'error',
  PLAYER_JOINED_ROOM = 'player_joined_room',
  PLAYER_LEFT_ROOM = 'player_left_room',
  DECKS_LIST = 'decks_list',
  DECK_CREATED = 'deck_created',
  DECK_DELETED = 'deck_deleted',
  DECK_SUBMITTED = 'deck_submitted',
  DECK_UPDATED = 'deck_updated',
}
