export enum GameCommands {
  CREATE_GAME = 'create_game',
  LIST_GAMES = 'list_games',
  JOIN_GAME = 'join_game',
  LEAVE_GAME = 'leave_game',
  CHALLENGE = 'challenge',
  COIN_TOSS_PICK = 'coin_toss_pick',
  COIN_TOSS_FLIP = 'coin_toss_flip',
  DECIDE_WHO_GOES_FIRST = 'decide_who_goes_first',
  CARD_DROP = 'card_drop',
  TAP_CARD = 'tap_card',
  UNTAP_CARD = 'untap_card',
  PHASE_CHANGE = 'phase_change',
  SEND_CHAT = 'send_chat',
  CREATE_DECK = 'create_deck',
  GET_DECKS = 'get_decks',
  DELETE_DECK = 'delete_deck',
  SUBMIT_DECK = 'submit_deck',
  UPDATE_DECK = 'update_deck',
}
